#!/bin/sh

HOME_DIR="/home/vagrant"

# Shared comes from shell provisioner in VagrantFile
DOWNLOAD_DIR="$SHARED_DIR/downloads"

DJATOKA_HOME="/usr/local/djatoka"

FEDORA_VERSION=3.8.0
FEDORA_HOME="/usr/local/fedora"

FFMPEG_VERSION=1.1.4

FITS_HOME="/usr/local/fits"
FITS_VERSION=0.8.5

SOLR_HOME="/usr/local/solr"
SOLR_VERSION=4.2.0

DRUPAL_LIBRARIES="/var/www/drupal/sites/all/libraries"
