#!/bin/bash
# shellcheck disable=SC2034

HOME_DIR="/home/vagrant"

# Shared comes from shell provisioner in VagrantFile
DOWNLOAD_DIR="$SHARED_DIR/downloads"

DJATOKA_HOME="/usr/local/djatoka"

FEDORA_HOME="/usr/local/fedora"

FFMPEG_VERSION=1.1.4

FITS_HOME="/usr/local/fits"
FITS_VERSION=1.1.1

SOLR_HOME="/usr/local/solr"
SOLR_VERSION=4.10.4

DRUPAL_HOME="/var/www/drupal"
